version: '2'

services:
  clion:
    build: .
    image: d.bigj.dev/clion:2019.3.2
    container_name: clion
    privileged: true
    volumes:
      - "/etc/fonts:/etc/fonts:ro"
      - "/usr/share/fonts:/usr/share/fonts:ro"

      - "/usr/share/gtk-3.0:/usr/share/gtk-3.0"
      - "/usr/share/themes:/usr/share/themes"

      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME:/root:rw"
    environment:
      - "VERSION=2019.3.2"

      - "DISPLAY=unix$DISPLAY"
      - "JAVA_HOME=/opt/clion/jre64"
    network_mode: "host"
